#!/bin/sh
set -e
pushd /home/smissingham/nixos-config &>/dev/null

# auto-format nix files
# capture errors for print but suppress the extra junk
echo "Formatting nix files"
for i in *.nix; do
  [ -f "$i" ] || break
  if ! out=$(alejandra "$i" 2>&1) && [ -n "$out" ]; then
    echo "$out" | grep -v "Checking" | grep -v -e '^$'
  fi
done

git --no-pager diff -U0 *.nix
echo "NixOS Rebuilding..."

sudo nixos-rebuild switch &>nixos-switch.log || (
cat nixos-switch.log | grep --color error && false)

echo "Committing to Repo"
generation=$(nixos-rebuild list-generations | grep current)

sh ./_copytoml

git add .
git commit -m "$generation"

popd